// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SchemaExamples.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class PageView : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""PageView"",""namespace"":""SchemaExamples.Model"",""fields"":[{""name"":""page_type"",""doc"":""The type of the page the user requested"",""default"":""Login"",""type"":{""type"":""enum"",""name"":""PageTypes"",""namespace"":""SchemaExamples.Model"",""symbols"":[""Login"",""LogOut"",""Dashboard"",""Settings"",""Reports"",""Other""]}},{""name"":""user_agent"",""doc"":""The user agent that made the request"",""type"":""string""},{""name"":""timestamp"",""doc"":""UTC time the request was made"",""type"":""long"",""logicalType"":""timestamp-millis""}]}");
		/// <summary>
		/// The type of the page the user requested
		/// </summary>
		private SchemaExamples.Model.PageTypes _page_type;
		/// <summary>
		/// The user agent that made the request
		/// </summary>
		private string _user_agent;
		/// <summary>
		/// UTC time the request was made
		/// </summary>
		private long _timestamp;
		public virtual Schema Schema
		{
			get
			{
				return PageView._SCHEMA;
			}
		}
		/// <summary>
		/// The type of the page the user requested
		/// </summary>
		public SchemaExamples.Model.PageTypes page_type
		{
			get
			{
				return this._page_type;
			}
			set
			{
				this._page_type = value;
			}
		}
		/// <summary>
		/// The user agent that made the request
		/// </summary>
		public string user_agent
		{
			get
			{
				return this._user_agent;
			}
			set
			{
				this._user_agent = value;
			}
		}
		/// <summary>
		/// UTC time the request was made
		/// </summary>
		public long timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.page_type;
			case 1: return this.user_agent;
			case 2: return this.timestamp;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.page_type = (SchemaExamples.Model.PageTypes)fieldValue; break;
			case 1: this.user_agent = (System.String)fieldValue; break;
			case 2: this.timestamp = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
